feature: support direct gesture translation via new animatesPositionWhileDragging modifier
fermoya/SwiftUIPager pull request #187
Opened 2021-02-14 16:21 UTC by nylki

This PR implements a new optional modifier `animatesPositionWhileDragging` whose default value is `true`.
The default value retains the current behaviour, so it shouldn't have any impact for users updating to a version including this PR.

If `animatesPositionWhileDragging`is set to `false`, the positions of the dragging gesture won't be animated/transitioned, resulting in a 1:1 tracking of finger to pager translation.

This targets and should resolve concerns raised in #157.

I made sure to add a short entry in the documentation. Could be expanded.

2021-02-14 19:26 UTC, fermoya commented
Hi @nylki thanks for your contribution. By the time [Issue 157](https://github.com/fermoya/SwiftUIPager/issues/157) was opened I had my concerns because of state management at the time. Things have changed and version `2.0.0`  introduced some changes. 

I think I'd prefer if there was no modifier at all and you just removed the `withAnimation` block. Could you also please remove the contents of `release_description.md` and write somethings like:
```
### Fixes
- # 157 <Add description>
```
I'll give it another look then and merge

2021-02-14 19:28 UTC, fermoya requested changes
Please, just remove the `withAnimation` block

2021-02-15 20:22 UTC, fermoya commented
Can we squash the commits into just one, please? See _Squashing commits_ section [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

2021-02-15 20:23 UTC, nylki commented
> Can we squash the commits into just one, please? See _Squashing commits_ section [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

I agree! Sorry for the mess. I'll just create a new PR with a clean branch.

2021-02-15 20:23 UTC, closed without merging

2021-02-15 20:57 UTC, nylki commented
@fermoya This is the fresh PR:  enhancement(animation): dont animate translate while dragging #188 
Let me know if you need additional changes.